import type { Rock } from "@ruiapp/move-style";
import RapidTextRenderer from "./rapid-text-renderer/RapidTextRenderer";
import RapidBoolRenderer from "./rapid-bool-renderer/RapidBoolRenderer";
import RapidDateTimeRenderer from "./rapid-date-time-renderer/RapidDateTimeRenderer";
import RapidJsonRenderer from "./rapid-json-renderer/RapidJsonRenderer";
import RapidReferenceRenderer from "./rapid-reference-renderer/RapidReferenceRenderer";
import RapidSelect from "./rapid-select/RapidSelect";
import RapidTable from "./rapid-table/RapidTable";
import RapidTableAction from "./rapid-table-action/RapidTableAction";
import RapidTableColumn from "./rapid-table-column/RapidTableColumn";
import RapidDescriptionsRenderer from "./rapid-descriptions-renderer/RapidDescriptionsRenderer";
import RapidForm from "./rapid-form/RapidForm";
import RapidFormItem from "./rapid-form-item/RapidFormItem";
import RapidToolbar from "./rapid-toolbar/RapidToolbar";
import RapidToolbarButton from "./rapid-toolbar-button/RapidToolbarButton";
import RapidToolbarLink from "./rapid-toolbar-link/RapidToolbarLink";
import RapidToolbarPageLink from "./rapid-toolbar-page-link/RapidToolbarPageLink";
import RapidArrayRenderer from "./rapid-array-renderer/RapidArrayRenderer";
import RapidObjectRenderer from "./rapid-object-renderer/RapidObjectRenderer";
import RapidDictionaryEntryRenderer from "./rapid-dictionary-entry-renderer/RapidDictionaryEntryRenderer";
import RapidDatePicker from "./rapid-date-picker/RapidDatePicker";
import RapidLinkRenderer from "./rapid-link-renderer/RapidLinkRenderer";
import RapidFileSizeRenderer from "./rapid-file-size-renderer/RapidFileSizeRenderer";
import RapidUploaderFormInput from "./rapid-uploader-form-input/RapidUploaderFormInput";
import RapidTreeSelect from "./rapid-tree-select/RapidTreeSelect";

const rapidRocks: Record<string, Rock> = {};
rapidRocks[RapidTextRenderer.$type] = RapidTextRenderer;
rapidRocks[RapidArrayRenderer.$type] = RapidArrayRenderer;
rapidRocks[RapidBoolRenderer.$type] = RapidBoolRenderer;
rapidRocks[RapidDatePicker.$type] = RapidDatePicker;
rapidRocks[RapidDateTimeRenderer.$type] = RapidDateTimeRenderer;
rapidRocks[RapidDescriptionsRenderer.$type] = RapidDescriptionsRenderer;
rapidRocks[RapidDictionaryEntryRenderer.$type] = RapidDictionaryEntryRenderer;
rapidRocks[RapidFileSizeRenderer.$type] = RapidFileSizeRenderer;
rapidRocks[RapidJsonRenderer.$type] = RapidJsonRenderer;
rapidRocks[RapidLinkRenderer.$type] = RapidLinkRenderer;
rapidRocks[RapidObjectRenderer.$type] = RapidObjectRenderer;
rapidRocks[RapidReferenceRenderer.$type] = RapidReferenceRenderer;
rapidRocks[RapidSelect.$type] = RapidSelect;
rapidRocks[RapidTable.$type] = RapidTable;
rapidRocks[RapidTableAction.$type] = RapidTableAction;
rapidRocks[RapidTableColumn.$type] = RapidTableColumn;
rapidRocks[RapidForm.$type] = RapidForm;
rapidRocks[RapidFormItem.$type] = RapidFormItem;
rapidRocks[RapidToolbar.$type] = RapidToolbar;
rapidRocks[RapidToolbarButton.$type] = RapidToolbarButton;
rapidRocks[RapidToolbarLink.$type] = RapidToolbarLink;
rapidRocks[RapidToolbarPageLink.$type] = RapidToolbarPageLink;
rapidRocks[RapidTreeSelect.$type] = RapidTreeSelect;
rapidRocks[RapidUploaderFormInput.$type] = RapidUploaderFormInput;
export const RapidRocks = rapidRocks;

export * from "./utility";

export * from "./rapid-types";
export * from "./rapid-text-renderer/rapid-text-renderer-types";
export * from "./rapid-json-renderer/rapid-json-renderer-types";
export * from "./rapid-link-renderer/rapid-link-renderer-types";
export * from "./rapid-date-picker/rapid-date-picker-types";
export * from "./rapid-descriptions-renderer/rapid-descriptions-renderer-types";
export * from "./rapid-dictionary-entry-renderer/rapid-dictionary-entry-renderer-types";
export * from "./rapid-file-size-renderer/rapid-file-size-renderer-types";
export * from "./rapid-reference-renderer/rapid-reference-renderer-types";
export * from "./rapid-select/rapid-select-types";
export * from "./rapid-form/rapid-form-types";
export * from "./rapid-form-item/rapid-form-item-types";
export * from "./rapid-table/rapid-table-types";
export * from "./rapid-table-action/rapid-table-action-types";
export * from "./rapid-table-column/rapid-table-column-types";
export * from "./rapid-toolbar/rapid-toolbar-types";
export * from "./rapid-toolbar-button/rapid-toolbar-button-types";
export * from "./rapid-toolbar-link/rapid-toolbar-link-types";
export * from "./rapid-toolbar-page-link/rapid-toolbar-page-link-types";
export * from "./rapid-uploader-form-input/rapid-uploader-form-input-types";
export * from "./rapid-tree-select/rapid-tree-select-types";
