export const entitySingularCodes = [
  'app_client',
  'app_nav_item',
  'base_employee',
  'base_equipment',
  'base_equipment_category',
  'base_form_field',
  'base_material',
  'base_material_breakdown',
  'base_material_breakdown_part',
  'base_material_category',
  'base_material_document',
  'base_material_flow',
  'base_material_flow_process',
  'base_material_flow_process_input',
  'base_material_flow_process_output',
  'base_partner',
  'base_partner_category',
  'base_prod_flow',
  'base_prod_flow_process',
  'base_prod_flow_template',
  'base_prod_flow_template_process',
  'base_prod_process',
  'base_prod_process_category',
  'base_unit',
  'base_unit_category',
  'base_warehouse',
  'bpm_business_activity',
  'bpm_business_application',
  'bpm_business_category',
  'bpm_business_process',
  'bpm_business_process_revision',
  'bpm_business_task',
  'ecm_document',
  'ecm_revision',
  'ecm_storage_object',
  'inspection_category',
  'inspection_characteristic',
  'inspection_characteristic_category',
  'inspection_instrument',
  'inspection_instrument_category',
  'inspection_method',
  'inspection_rule',
  'inspection_sheet',
  'inspection_sheet_record',
  'data_dictionary',
  'data_dictionary_entry',
  'model',
  'property',
  'route',
  'oc_department',
  'oc_role',
  'oc_shop',
  'oc_user',
  'production_order',
  'production_order_item',
  'production_plan',
  'production_plan_item',
  'production_task',
  'production_work_report',
  'purchase_order',
  'purchase_order_item',
  'webhook',
  'warehouse_inventory',
  'warehouse_region',
  'warehouse_transfer',
  'warehouse_transfer_category',
  'warehouse_transfer_item',
] as const;
export type TEntitySingularCodes = typeof entitySingularCodes[number];

const entityFieldCodes = {
  'AppClient': [
    'code',
    'name',
    'config',
    'state',
  ],
  'AppNavItem': [
    'code',
    'name',
    'client',
    'parent',
    'orderNum',
    'icon',
    'pageCode',
    'config',
    'state',
  ],
  'BaseEmployee': [
    'code',
    'name',
    'shop',
    'department',
    'state',
  ],
  'BaseEquipment': [
    'code',
    'name',
    'category',
    'state',
    'powerState',
    'productionState',
    'planedDailyWorkingTime',
  ],
  'BaseEquipmentCategory': [
    'name',
    'orderNum',
    'parent',
    'equipments',
  ],
  'BaseFormField': [
    'code',
    'name',
    'fieldType',
    'state',
    'description',
  ],
  'BaseMaterial': [
    'code',
    'name',
    'description',
    'category',
    'canProduce',
    'canPurchase',
    'canSale',
    'state',
    'productionPlanItems',
  ],
  'BaseMaterialBreakdown': [
    'material',
    'version',
    'amount',
    'unit',
    'state',
    'parts',
  ],
  'BaseMaterialBreakdownPart': [
    'materialBreakdown',
    'orderNum',
    'subMaterial',
    'amount',
    'unit',
  ],
  'BaseMaterialCategory': [
    'name',
    'orderNum',
    'parent',
    'materials',
  ],
  'BaseMaterialDocument': [
    'material',
    'document',
    'state',
  ],
  'BaseMaterialFlow': [
    'material',
    'version',
    'state',
    'publishState',
    'processes',
  ],
  'BaseMaterialFlowProcess': [
    'materialFlow',
    'orderNum',
    'process',
    'aliasName',
    'inputs',
    'outputs',
    'standardCycleTime',
    'config',
  ],
  'BaseMaterialFlowProcessInput': [
    'materialProcess',
    'material',
    'amount',
    'unit',
    'config',
  ],
  'BaseMaterialFlowProcessOutput': [
    'materialProcess',
    'material',
    'amount',
    'unit',
    'config',
  ],
  'BasePartner': [
    'code',
    'name',
    'categories',
  ],
  'BasePartnerCategory': [
    'code',
    'name',
  ],
  'BaseProdFlow': [
    'name',
    'version',
    'state',
    'processes',
  ],
  'BaseProdFlowProcess': [
    'flow',
    'orderNum',
    'process',
    'standardCycleTime',
  ],
  'BaseProdFlowTemplate': [
    'name',
    'processes',
  ],
  'BaseProdFlowTemplateProcess': [
    'flowTemplate',
    'process',
    'standardCycleTime',
  ],
  'BaseProdProcess': [
    'code',
    'name',
    'category',
    'orderNum',
    'standardCycleTime',
  ],
  'BaseProdProcessCategory': [
    'code',
    'name',
    'orderNum',
  ],
  'BaseUnit': [
    'code',
    'name',
    'nameEn',
    'printSymbol',
    'type',
    'orderNum',
    'category',
  ],
  'BaseUnitCategory': [
    'name',
    'orderNum',
    'units',
  ],
  'BaseWarehouse': [
    'code',
    'name',
  ],
  'BpmBusinessActivity': [
    'application',
    'name',
    'kind',
    'tasks',
    'state',
    'resolution',
  ],
  'BpmBusinessApplication': [
    'process',
    'code',
    'title',
    'formData',
    'initiator',
    'initiatedAt',
    'approvedAt',
    'state',
  ],
  'BpmBusinessCategory': [
    'name',
    'orderNum',
  ],
  'BpmBusinessProcess': [
    'category',
    'name',
    'description',
    'formConfig',
    'flowConfig',
    'listConfig',
    'advancedConfig',
    'state',
    'publishState',
    'activeRevision',
  ],
  'BpmBusinessProcessRevision': [
    'process',
    'name',
    'description',
    'formConfig',
    'flowConfig',
    'advancedConfig',
    'publishState',
  ],
  'BpmBusinessTask': [
    'activity',
    'assignee',
    'state',
    'resolution',
  ],
  'EcmDocument': [
    'code',
    'name',
    'extName',
    'title',
    'size',
    'lastRevision',
    'storageObject',
    'ref',
    'parent',
    'publishState',
  ],
  'EcmRevision': [
    'document',
    'size',
    'storageObject',
    'publishState',
  ],
  'EcmStorageObject': [
    'size',
    'key',
    'hash',
  ],
  'InspectionCategory': [
    'code',
    'name',
  ],
  'InspectionCharacteristic': [
    'rule',
    'name',
    'category',
    'method',
    'instrumentCategory',
    'instrument',
    'config',
  ],
  'InspectionCharacteristicCategory': [
    'name',
    'description',
  ],
  'InspectionInstrument': [
    'code',
    'category',
  ],
  'InspectionInstrumentCategory': [
    'name',
    'description',
  ],
  'InspectionMethod': [
    'name',
    'description',
  ],
  'InspectionRule': [
    'category',
    'material',
    'materialProcess',
    'config',
  ],
  'InspectionSheet': [
    'code',
    'state',
    'productionTask',
    'rule',
    'materialProcess',
    'inspector',
    'records',
  ],
  'InspectionSheetRecord': [
    'sheet',
    'sampleCode',
    'characteristic',
    'instrumentCategory',
    'instrument',
    'inspectedAt',
    'actualValue',
  ],
  'DataDictionary': [
    'code',
    'name',
    'valueType',
    'level',
    'description',
    'source',
    'externalId',
    'externalData',
    'state',
    'entries',
  ],
  'DataDictionaryEntry': [
    'dictionary',
    'value',
    'name',
    'color',
    'icon',
    'description',
    'disabled',
    'orderNum',
  ],
  'Model': [
    'namespace',
    'name',
    'description',
    'singularCode',
    'pluralCode',
    'properties',
  ],
  'Property': [
    'model',
    'type',
    'name',
    'code',
    'description',
    'columnName',
    'required',
    'defaultValue',
    'config',
    'autoIncrement',
    'minLength',
    'maxLength',
    'relation',
    'targetSingularCode',
    'targetIdColumnName',
    'selfIdColumnName',
    'linkSchema',
    'linkTableName',
    'dataDictionary',
  ],
  'Route': [
    'namespace',
    'code',
    'name',
    'description',
    'type',
    'method',
    'endpoint',
    'handlers',
  ],
  'OcDepartment': [
    'parent',
    'code',
    'name',
    'orderNum',
    'users',
  ],
  'OcRole': [
    'name',
    'description',
    'orderNum',
    'state',
    'users',
  ],
  'OcShop': [
    'code',
    'name',
    'orderNum',
    'state',
  ],
  'OcUser': [
    'name',
    'login',
    'password',
    'hidden',
    'state',
    'email',
    'department',
    'roles',
  ],
  'ProductionOrder': [
    'code',
    'productionPlan',
    'assignmentState',
    'executionState',
    'material',
    'materialFlow',
    'amount',
    'unit',
    'scheduledStartDate',
    'scheduledFinishDate',
    'actualStartDate',
    'actualFinishDate',
    'productionTasks',
    'lineItems',
  ],
  'ProductionOrderItem': [
    'productionOrder',
    'material',
    'amount',
    'unit',
  ],
  'ProductionPlan': [
    'code',
    'scheduledStartDate',
    'scheduledFinishDate',
    'actualStartDate',
    'actualFinishDate',
    'scheduleState',
    'executionState',
    'lineItems',
    'productionOrders',
  ],
  'ProductionPlanItem': [
    'productionPlan',
    'material',
    'amount',
    'unit',
  ],
  'ProductionTask': [
    'code',
    'productionOrder',
    'material',
    'materialFlow',
    'materialProcess',
    'scheduledStartDate',
    'scheduledFinishDate',
    'actualStartDate',
    'actualFinishDate',
    'amount',
    'unit',
    'equipment',
    'assignees',
    'deadline',
    'assigner',
    'assignedAt',
    'acceptedAt',
    'assignmentState',
    'executionState',
    'workReports',
    'inspectionSheets',
  ],
  'ProductionWorkReport': [
    'code',
    'productionTask',
    'amount',
    'unit',
    'operators',
  ],
  'PurchaseOrder': [
    'code',
    'supplier',
    'lineItems',
  ],
  'PurchaseOrderItem': [
    'order',
    'material',
    'amount',
    'unit',
  ],
  'Webhook': [
    'name',
    'url',
    'secret',
    'namespace',
    'modelSingularCode',
    'events',
    'enabled',
  ],
  'WarehouseInventory': [
    'warehouse',
    'material',
    'region',
    'transferCode',
    'amount',
    'unit',
  ],
  'WarehouseRegion': [
    'warehouse',
    'code',
    'name',
  ],
  'WarehouseTransfer': [
    'warehouse',
    'code',
    'category',
    'approvalState',
    'currentApprovalStep',
  ],
  'WarehouseTransferCategory': [
    'code',
    'name',
  ],
  'WarehouseTransferItem': [
    'transfer',
    'fromRegion',
    'toRegion',
    'material',
    'amount',
    'unit',
  ],
} as const;
export type TEntityFieldCodes = typeof entityFieldCodes;
export type TEntityCodes = keyof TEntityFieldCodes;
